### ISSUE TITLE
ResourceRelation ON DELETE bahavior

### ISSUE THREAD

**Issue by zzFluke** [Lv-465-Java/TBRM.api#75]
@billyxd3, this is what we have been talking about FK constraints ON DELETE behavior: https://github.com/Lv-465-Java/TBRM.api/blob/18571dcc67ad305564fad3465a3f6cf05122599d/src/main/java/com/softserve/rms/repository/implementation/JooqDDL.java#L140

JOOQ even has [a dedicate API](https://www.jooq.org/javadoc/3.9.1/org/jooq/ConstraintForeignKeyOnStep.html) for specifying ON DELETE behavior, e.g. :
```
org.jooq.impl.DSL
    .constraint(String name)
    .foreignKey(String field1)
    .references​(String table)
    .onDeleteCascade()
```
Given this, it's easy to make it configurable on the [ResourceRelation](https://github.com/Lv-465-Java/TBRM.api/blob/develop/src/main/java/com/softserve/rms/entities/ResourceRelation.java). Where can be a simple *enum* with the type of the relationship: *Master-Detail* or *Lookup*.

- *Master-Detail* means Master record controls Detail records and wipe them out once it has deleted.
- *Lookup* can be something like `onDeleteSetNull()`.

On a highlevel this is how [Salesforce object relationships](https://help.salesforce.com/articleView?id=overview_of_custom_object_relationships.htm&type=5) implemented, but they have much broader impact.

The default behavior that you explained documented [here](https://www.postgresql.org/docs/9.5/ddl-constraints.html#DDL-CONSTRAINTS-FK):

> NO ACTION means that if any referencing rows still exist when the constraint is checked, an error is raised; this is the default behavior if you do not specify anything

**Comment by billyxd3** [comment]
I have done it.
https://gist.github.com/billyxd3/9094059728966b16fbd17614004a1231

**Comment by zzFluke** [comment]
👍 ship it
