### ISSUE TITLE
API design for Resource records

### ISSUE THREAD

**Issue by zzFluke** [Lv-465-Java/TBRM.api#81]
https://github.com/Lv-465-Java/TBRM.api/blob/18571dcc67ad305564fad3465a3f6cf05122599d/src/main/java/com/softserve/rms/controller/ResourceRecordController.java#L26

To me it looks weird @RequestMapping("/resource-template/resource/{tableName}")
ResourceRecord is no more a blueprint (template) it's a "physical" place to store records. So, if this was my API I would say something like: @RequestMapping("/resource/{resourceName}")

**Comment by billyxd3** [comment]
Done it.
https://github.com/Lv-465-Java/TBRM.api/commit/a084051cc7b20ca790ababe675a4cb042065f55b

**Comment by zzFluke** [comment]
🚢 it!
